# -*- coding: utf-8 -*-
"""1DGaussian.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cvne9dJ8AbKFgd11kvPK7gYS0AEFFdFp

#  <font color='red'> Review of 1D Gaussian distribution </font>
"""

import matplotlib.pyplot as plt
from matplotlib import cm

import numpy as np
import scipy as sc
from scipy.stats import multivariate_normal



"""## Set mean and standard deviation and plot the pdf

You may vary the parameters and see how the plots change

The following code represents the equation of Gaussian Distribution:
    $$N(x|\mu, \sigma^2) = \frac{1}{(2\pi\sigma^2)^{\frac{1}{2}}}\exp(\frac{-\delta^2}{2})$$
where $$\delta = \frac{x-\mu}{\sigma}$$ 

"""

# Parameters of the Gaussian

mu = 1      # mean
sigma = 1 # standard deviation

Nsamples = 600  # Sample size
x = np.linspace(-8, 8, Nsamples)    # Hover over "linspace" to see detailed explanation
Deltax = x[1]-x[0]

Delta_squared = np.square((x-mu)/sigma)
pdf = 1/np.sqrt(2*np.pi*np.square(sigma))*np.exp(-Delta_squared/2)

# Plot of the Gaussian PDF
s = plt.plot(x, pdf)

# Check if the integral ~ 1
sum(pdf)*Deltax

"""## Draw samples from the distribution and plot

See https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html
"""

N=10000

s = np.random.normal(mu, sigma, N)
pt = plt.hist(s, bins=x)
pt = plt.xlabel('x')
pt = plt.ylabel('histogram')